<?php

if (!defined('SERVIDOR')) define('SERVIDOR', 'localhost');
if (!defined('USUARIO')) define('USUARIO', 'root');
if (!defined('PASS')) define('PASS', '');
if (!defined('BD')) define('BD', 'book2');

$servidor = "localhost";
$usuario = "root";
$pass = "";
$bd = "book2";

$emailhost = "mx1.hostinger.es";
$emailusername = "support@book2book.tk"; 
$emailpassword = "lWL5VGdTZB";
$emailpuerto = 2525;

?>